### PR TITLE
Include user/pass in channel URL

### PR DESCRIPTION
**Pull request by tenfire**
This solved #26 for me

### CODE REVIEW

**Comment by TheJF** [comment]
So this used to be the way things were done with Tvheadend, but then they changed the auth logic. I'll test further (as nothing seems to work and I'm really hating Tvheadend at the moment) but it's possible this fixes older setups and breaks newer setups. Which would be a huge pain.

I'm hoping it'll work for both however.

**Comment by Marlinc** [comment]
This is working for me using TVHeadend 4.3-1852~gdea96e441

**Comment by ledfloyd1984** [comment]
@jfarseneau Could you please approve this PR and create a new release please? I know that this is practically a dead repo, but it would still benefit my situation greatly.

**Comment by jfarseneau** [comment]
Sure, this is indeed a dead repo, and I have no way to test it right now, but I'll take tenfire and Marlinc's word for it. Merging!

And this is very late, but thank you @tenfire for the contribution. Happy new year!

**Pull request merged**
